# Generated by Django 4.1.2 on 2022-11-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='Понедельник', max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_lessons', to='users.mentormodel')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mentors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_book', to='users.mentormodel')),
                ('peer_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='str_pr', to='users.studentsmodel')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_table', to='diary.timetable')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_book', to='users.studentsmodel')),
            ],
            options={
                'verbose_name': 'Дневники',
            },
        ),
    ]
