# Generated by Django 4.0.4 on 2022-11-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='peer_review',
            new_name='peer_to_peer',
        ),
    ]
