# Generated by Django 4.1.2 on 2022-11-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Data Science', 'Data Science'), ('Full-Stack', 'Full-Stack')], default='Software Engineer', max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='MentorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('birth_place', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('course_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='users.courses')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_work', to='users.homework')),
            ],
            options={
                'verbose_name': 'Ментор',
                'verbose_name_plural': 'Менторы',
            },
        ),
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('birth_place', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('astro_purchase', models.CharField(max_length=255)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_home_work', to='users.homework')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_mentor', to='users.mentormodel')),
                ('std_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_course', to='users.courses')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
